/**
 * Builds a Bootstrap Icons subset with only the glyphs the site uses.
 *
 * The full icon font is 134 KB and its CSS ~2,000 rules (~95 KB), all of it
 * render-blocking, for roughly a hundred icons. This scans the source for
 * `bi-<name>` and writes a small font plus its CSS into src/styles/generated/.
 * Runs before every build (npm "prebuild"); the output is committed so a dev
 * server works without running it.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconsDir = join(root, 'node_modules/bootstrap-icons/font');
const outDir = join(root, 'src/styles/generated');
// Served from static/ like the other fonts: Vite does not rebase url() inside an @import-ed Sass partial.
const fontDir = join(root, 'static/fonts');

/**
 * Icons whose names never appear literally in this repo: social platforms
 * picked from the database at runtime (lib/social.ts, Navbar/Footer icon maps)
 * and the ones in HTML the API renders (mokultur-elysia shortcodes, read-also,
 * story images). Add a name here if it comes from data.
 */
const EXTRA = [
  'facebook', 'instagram', 'tiktok', 'twitter', 'twitter-x', 'youtube', 'threads', 'whatsapp', 'telegram', 'linkedin',
  'discord', 'spotify', 'twitch', 'github', 'reddit', 'pinterest', 'snapchat', 'line', 'globe', 'globe2', 'link', 'link-45deg', 'envelope',
  'arrow-return-right', 'arrow-right', 'camera-reels-fill', 'graph-up-arrow', 'patch-check-fill', 'people-fill', 'person-fill',
];

const map = JSON.parse(readFileSync(join(iconsDir, 'bootstrap-icons.json'), 'utf8'));
const used = new Set(EXTRA.filter((name) => name in map));
// Styles that draw a glyph by codepoint (content: "\F28A"; font-family: "bootstrap-icons") need it in the font too.
const rawCodepoints = new Set();
const walk = (dir) => {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) { if (entry !== 'generated') walk(path); continue; }
    if (!/\.(svelte|ts|js|html|scss|css)$/.test(entry)) continue;
    const text = readFileSync(path, 'utf8');
    for (const [, name] of text.matchAll(/\bbi-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) {
      if (name in map) used.add(name);
    }
    if (text.includes('bootstrap-icons')) {
      for (const [, hex] of text.matchAll(/content:\s*["']\\([0-9a-fA-F]{4,5})["']/g)) rawCodepoints.add(parseInt(hex, 16));
    }
  }
};
walk(join(root, 'src'));

const names = [...used].sort();
const glyphs = new Set([...names.map((n) => map[n]), ...rawCodepoints]);
const font = await subsetFont(readFileSync(join(iconsDir, 'fonts/bootstrap-icons.woff2')), [...glyphs].map((c) => String.fromCodePoint(c)).join(''), { targetFormat: 'woff2' });

// The file name stays fixed, so the URL carries a content hash to bust caches when the icon set changes.
const version = createHash('sha1').update(font).digest('hex').slice(0, 10);

// Keep the upstream base rules (.bi::before …) verbatim; replace only @font-face and the per-icon list.
const upstream = readFileSync(join(iconsDir, 'bootstrap-icons.css'), 'utf8');
const base = upstream.slice(upstream.indexOf('.bi::before'), upstream.indexOf('.bi-123::before'));
const css = `/* Generated by scripts/build-icons.mjs from bootstrap-icons ${JSON.parse(readFileSync(join(root, 'node_modules/bootstrap-icons/package.json'), 'utf8')).version}. Do not edit. ${names.length} icons. */
@font-face {
  font-display: block;
  font-family: "bootstrap-icons";
  src: url("/fonts/bootstrap-icons-subset.woff2?v=${version}") format("woff2");
}

${base.trim()}

${names.map((n) => `.bi-${n}::before { content: "\\${map[n].toString(16)}"; }`).join('\n')}
`;

mkdirSync(outDir, { recursive: true });
mkdirSync(fontDir, { recursive: true });
writeFileSync(join(fontDir, 'bootstrap-icons-subset.woff2'), font);
rmSync(join(outDir, 'bootstrap-icons-subset.woff2'), { force: true });
writeFileSync(join(outDir, '_bootstrap-icons-subset.scss'), css);
console.log(`bootstrap-icons subset: ${names.length} icons (+${rawCodepoints.size} raw glyphs), ${(font.length / 1024).toFixed(1)} KB font`);
